In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, 

In [9]:
model = Sequential()
model.add(Embedding(100, 64, input_length=10))
# 模型将输入一个大小为 (batch, input_length) 的整数矩阵。
# 输入中最大的整数（即词索引）不应该大于 999 （词汇表大小）
# 现在 model.output_shape == (None, 10, 64)，其中 None 是 batch 的维度。

input_array = np.random.randint(100, size=(32, 10))

model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
assert output_array.shape == (32, 10, 64)

In [5]:
np.random.randint(3, size=(10,1))

array([[1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1]])

In [4]:
import tensorflow as tf
import numpy  as np
from tensorflow.keras.layers import Layer

In [3]:
raw_inputs = [
    [711, 632, 71],
    [73, 8, 3215, 55, 927],
    [83, 91, 1, 645, 1253, 927],
]

# By default, this will pad using 0s; it is configurable via the
# "value" parameter.
# Note that you could "pre" padding (at the beginning) or
# "post" padding (at the end).
# We recommend using "post" padding when working with RNN layers
# (in order to be able to use the
# CuDNN implementation of the layers).
padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
    raw_inputs, padding="post"
)
print(padded_inputs)

[[ 711  632   71    0    0    0]
 [  73    8 3215   55  927    0]
 [  83   91    1  645 1253  927]]


In [6]:
class CustomerLayer(Layer):

    def __init__(self, trainable=True, name=None, dtype=None, dynamic=False, **kwargs):
        super().__init__(trainable=trainable, name=name, dtype=dtype, dynamic=dynamic, **kwargs)

    
    def call(self, inputs, mask=None):
        if mask is None:
            return inputs
        print(mask)
        return inputs 

    def compute_mask(self, inputs, mask=None):
        if mask is None:
            return None 
        return tf.cast(mask, tf.int32)

In [8]:
inputs = tf.keras.layers.Input(shape=(20,), dtype="int32")
x = tf.keras.layers.Embedding(input_dim=32, output_dim=16, mask_zero=True)(inputs)
x = CustomerLayer()(x)  # Will pass the mask along

print("Mask found:", x._keras_mask)
outputs = tf.keras.layers.Dense(10, activation="relu")(x)
model = tf.keras.Model(inputs, outputs)

model = tf.keras.Model(inputs, outputs)

Tensor("Placeholder_1:0", shape=(None, 20), dtype=bool)
Mask found: KerasTensor(type_spec=TensorSpec(shape=(None, 20), dtype=tf.int32, name=None), name='Cast:0')


In [19]:
feautres = np.random.random(size=(32, 20))
labels = np.random.randint(2, size=(32, 1))

In [20]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics="auc")

In [21]:
model.fit(feautres,
          labels)

Tensor("model_1/embedding_2/NotEqual:0", shape=(32, 20), dtype=bool)


ValueError: in user code:

    File "D:\Program Files (x86)\Anaconda3\envs\recommender\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "D:\Program Files (x86)\Anaconda3\envs\recommender\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "D:\Program Files (x86)\Anaconda3\envs\recommender\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "D:\Program Files (x86)\Anaconda3\envs\recommender\lib\site-packages\keras\engine\training.py", line 810, in train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    File "D:\Program Files (x86)\Anaconda3\envs\recommender\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "D:\Program Files (x86)\Anaconda3\envs\recommender\lib\site-packages\keras\losses.py", line 143, in __call__
        losses, sample_weight, reduction=self._get_reduction())
    File "D:\Program Files (x86)\Anaconda3\envs\recommender\lib\site-packages\keras\utils\losses_utils.py", line 322, in compute_weighted_loss
        losses, None, sample_weight)
    File "D:\Program Files (x86)\Anaconda3\envs\recommender\lib\site-packages\keras\utils\losses_utils.py", line 211, in squeeze_or_expand_dimensions
        sample_weight = tf.squeeze(sample_weight, [-1])

    ValueError: Can not squeeze dim[1], expected a dimension of 1, got 20 for '{{node binary_crossentropy/weighted_loss/Squeeze}} = Squeeze[T=DT_FLOAT, squeeze_dims=[-1]](Cast)' with input shapes: [32,20].


In [15]:
feautres

array([[9.70571824e-01, 2.79704992e-01, 8.56489056e-01, 2.89744653e-01,
        2.48587890e-02, 1.43565596e-01, 1.59611861e-01, 8.20256627e-01,
        7.00561225e-01, 4.04111835e-01, 6.04652957e-01, 5.59594641e-01,
        1.84049437e-01, 5.71397620e-02, 6.41771262e-01, 4.41420305e-01,
        3.16935054e-01, 8.84271496e-01, 8.10940293e-02, 3.85923642e-01],
       [4.96017952e-02, 3.33184224e-01, 5.18078076e-01, 1.19746250e-01,
        9.57261457e-01, 2.15417460e-01, 6.74074146e-01, 9.60789371e-01,
        3.60818695e-01, 1.90424962e-01, 6.60218777e-01, 2.64762099e-01,
        2.28461145e-01, 8.71832633e-01, 4.43122340e-01, 4.64001604e-01,
        2.05319519e-02, 4.95700749e-01, 8.24118606e-01, 3.64902782e-01],
       [6.38270206e-02, 8.78128703e-02, 3.21306391e-01, 9.34529686e-02,
        6.28054727e-01, 6.61365341e-01, 1.92797016e-03, 3.64286142e-01,
        2.10324419e-01, 3.32363127e-01, 3.86598867e-01, 2.02862213e-01,
        1.38389978e-01, 3.30556544e-01, 6.31458829e-01, 3.0308

In [13]:
feautres

0.02669295166718988